export const handlerProperties = {
  tracker: ["read", "list", "post", "put"],
  project_tracker: ["list"],
  tracker_commit_convfactor: ["list", "post", "put"],
  tracker_ref_head: ["put"],
  tracker_commit_target: ["list", "post", "put", "patch", "delete"],
  tracker_ref_tree_tree_and_metric: ["post"],
  tracker_commit_value: ["list", "post"],
  tracker_commit_score_value: ["post", "put"],
  tracker_ref_tree_score: ["patch"],
  tracker_ref_tree_document: ["post"],
  //tracker_commit_document_object: ["list"],
  tracker_ref_document: ["put", "delete"],
  tracker_ref_tree_tree: ["post"],
  tracker_ref_tree: ["delete", "post"],
  tracker_commit_tree_comment: ["list", "post"],
  tracker_commit_indicator: ["list", "post", "put", "delete"],
  tracker_ref_all: ["list"],
  tracker_ref: ["list", "read", "patch", "post", "delete"],
  tracker_ref_tree_branch: ["post"],
  tracker_ref_submodule: ["list"],
  tracker_ref_branch: ["post", "put"],
  company_target: ["list", "post", "put", "patch"],
  company_member: ["list", "delete"],
  company: ["list", "read", "post", "put", "delete"],
  company_authgroup: ["list", "post", "put"],
  company_permission: ["list"],
  company_invite: ["list", "post", "put", "delete"],
  company_invite_all: ["list"],
  company_report: ["list"],
  company_report_excel: ["list"],
  company_indicator: ["list", "post", "delete"],
  project_reporting_periods: ["list", "delete"],
  project_reporting_periods_excel: ["list"],
  project_reporting_periods_commits: ["list"],
  project_reporting_periods_inputs: ["list"],
  project_discipline: ["list", "post", "put", "delete"],
  project_invite: ["list", "post", "put", "delete"],
  project_invite_all: ["list"],
  project_email_recipient: ["list", "read", "put", "patch"],
  project_authgroup: ["list", "post", "put"],
  project_permission: ["list"],
  project_member: ["list", "delete"],
  project: ["list", "post", "put", "patch", "read", "delete"],
  project_and_setup: ["post"],
  tracker_commit_edge: ["read", "put"],
  tracker_branch: ["list"],
  tracker_commit_branch: ["list"],
  tracker_ref_commit: ["list", "post", "put"],
  tracker_commit_all: ["list"]
};
