"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.RESET_FAILURE = exports.RESET_PENDING = exports.RESET_SUCCESS = exports.ACTIVATE_FAILURE = exports.ACTIVATE_SUCCESS = exports.REGISTER_FAILURE = exports.REGISTER_SUCCESS = exports.LOGIN_FAILURE = exports.LOGIN_STATUS = exports.LOGIN_SUCCESS = void 0;
var LOGIN_SUCCESS = 'LOGIN_SUCCESS';
exports.LOGIN_SUCCESS = LOGIN_SUCCESS;
var LOGIN_STATUS = 'LOGIN_STATUS';
exports.LOGIN_STATUS = LOGIN_STATUS;
var LOGIN_FAILURE = 'LOGIN_FAILURE';
exports.LOGIN_FAILURE = LOGIN_FAILURE;
var REGISTER_SUCCESS = 'REGISTER_SUCCESS';
exports.REGISTER_SUCCESS = REGISTER_SUCCESS;
var REGISTER_FAILURE = 'REGISTER_FAILURE';
exports.REGISTER_FAILURE = REGISTER_FAILURE;
var ACTIVATE_SUCCESS = 'ACTIVATE_SUCCESS';
exports.ACTIVATE_SUCCESS = ACTIVATE_SUCCESS;
var ACTIVATE_FAILURE = 'ACTIVATE_FAILURE';
exports.ACTIVATE_FAILURE = ACTIVATE_FAILURE;
var RESET_SUCCESS = 'RESET_SUCCESS';
exports.RESET_SUCCESS = RESET_SUCCESS;
var RESET_PENDING = 'RESET_PENDING';
exports.RESET_PENDING = RESET_PENDING;
var RESET_FAILURE = 'RESET_FAILURE';
exports.RESET_FAILURE = RESET_FAILURE;